name: gcoopcali
favicon: null
layout_spectrum: 0.6857853080146015
typography_spectrum: 0.341918429126963
title: GCoopCali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#000000'
    - '#3a3a3a'
    - '#cecece'
  brandStrength: 0.5
  lightness: 0.6416287610772997
  saturation: 0.48646759265102446
  rhythmicContrast: 0.36214782507158816
purpose: []
