name: gcoopcali
favicon: null
layout_spectrum: 0.6857853080146015
typography_spectrum: 0.341918429126963
title: GCoopCali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7972829982172698
  lightness: 0.6416287610772997
  saturation: 0.48646759265102446
  rhythmicContrast: 0.36214782507158816
purpose: []
